name: Git Version

on:
  push:
    branches:
      - trunk

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: commits
        run: |
          echo ${{ github.event.commits }}
      - name: event
        run: |
          echo ${{ github.event }}
