name: Build and Push Tag and Image
on:
  push:
    branches:
      - trunk
jobs:
  tag:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - 
      name: Push tag
      run: |
          git tag ${{github.run_id}}
          git push origin ${{github.run_id}}
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ubiquitous-spoon:${{ github.run_id }}
    - 
      name: Checkout Gitops
      uses: actions/checkout@v3
      with:
        repository: audryus/gitops-argo
        persist-credentials: false
        fetch-depth: 0
    - 
      name: Update manifests
      run: |
        sleep 1
        cd ubiquitous-spoon/overlays/dev/
        cat rollout.yaml | sed 's/${{ secrets.DOCKERHUB_USERNAME }}\/ubiquitous-spoon:.*/${{ secrets.DOCKERHUB_USERNAME }}\/ubiquitous-spoon:${{ github.run_id }}/' | tee rollout.yaml
        git config --global user.email "audryus@gmail.com"
        git config --global user.name "GitHub Action"
        git add .
        git commit -m "Promoting ubiquitous-spoon ${{ github.run_id }}"
    - 
      name: Push Git
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
        repository: audryus/ubiquitous-spoon
